/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus_ticket_booking;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author harid
 */
public class Admin_fPass extends javax.swing.JFrame {

    /**
     * Creates new form Admin_fPass
     */
    public Admin_fPass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        forgetpass = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        phnno = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        txtphn = new javax.swing.JTextField();
        check = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        forgetpass.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        forgetpass.setText("Forget password");
        jPanel1.add(forgetpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        email.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        email.setText("Email Id");
        email.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 30));

        phnno.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        phnno.setText("Phone No");
        phnno.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.add(phnno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        txtmail.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txtmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 200, -1));

        txtphn.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txtphn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphnActionPerformed(evt);
            }
        });
        jPanel1.add(txtphn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 200, -1));

        check.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        check.setText("check");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        jPanel1.add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        exit.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, 30));

        background.setIcon(new javax.swing.ImageIcon("D:\\java programs\\Project Reqirements\\Images\\Edited files\\4d845686128681.5d909dad4ddd3.jpg")); // NOI18N
        background.setToolTipText("");
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -36, 510, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtphnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphnActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
   
        String mail= txtmail.getText();
       int phn= Integer.parseInt(txtphn.getText());
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/bus_ticket_booking","root","");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from admin_accountcreation");
            while(rs.next())
                    {
                        if(mail.equals(rs.getString(3))&&rs.getInt(2)==phn)
                                {
                                    JOptionPane.showMessageDialog(this,rs.getString(1));
                                    Admin_Changepass ac=new Admin_Changepass();
                                    ac.setVisible(true);
                                    break;
                                }
//                        if(!mail.equals(rs.getString(3))&&rs.getInt(2)!=phn)
//                        {
//                            JOptionPane.showMessageDialog(this, "The Enter number are not registered");
//                            break;
//                        }
                    }
            con.close();
          
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Admin_fPass.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Admin_fPass.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }//GEN-LAST:event_checkActionPerformed

    private void txtmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmailActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
this.setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_fPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_fPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_fPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_fPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_fPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton check;
    private javax.swing.JLabel email;
    private javax.swing.JButton exit;
    private javax.swing.JLabel forgetpass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel phnno;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtphn;
    // End of variables declaration//GEN-END:variables
}
