/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus_ticket_booking;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.print.attribute.Size2DSyntax.MM;
import javax.swing.JOptionPane;

/**
 *
 * @author harid
 */
public class Admin_Control extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Control
     */
    public Admin_Control() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AdminControl = new javax.swing.JLabel();
        Travelsname = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        ac = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        txtbus = new javax.swing.JComboBox<>();
        txtlocation = new javax.swing.JComboBox<>();
        txttime = new javax.swing.JTextField();
        txtac = new javax.swing.JComboBox<>();
        txtdate = new com.toedter.calendar.JDateChooser();
        txtseatsavail = new javax.swing.JTextField();
        date1 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        txtprize = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminControl.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        AdminControl.setText("Admin Control");
        jPanel1.add(AdminControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 11, -1, -1));

        Travelsname.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        Travelsname.setText("Travels Name");
        jPanel1.add(Travelsname, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 110, -1, -1));

        location.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        location.setText(" Location");
        jPanel1.add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 170, -1, -1));

        time.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        time.setText(" Time");
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 229, -1, -1));

        ac.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        ac.setText("AC ");
        jPanel1.add(ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 287, -1, -1));

        date.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        date.setText("Date");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 355, -1, -1));

        txtbus.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txtbus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KPN Travels", "Parveen Travels", "SRS Travels", "ABT Travels" }));
        txtbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbusActionPerformed(evt);
            }
        });
        jPanel1.add(txtbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 109, 207, 28));

        txtlocation.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txtlocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pollachi-Chennai", "Coimbatore-Chennai", "Coimbatore-Madurai", "Madurai-Coimbatore" }));
        jPanel1.add(txtlocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 174, 207, 27));

        txttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimeActionPerformed(evt);
            }
        });
        jPanel1.add(txttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 233, 207, 27));

        txtac.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txtac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jPanel1.add(txtac, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 291, 207, 27));

        txtdate.setDateFormatString("yyyy-MM-dd");
        txtdate.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jPanel1.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 355, 207, 28));
        jPanel1.add(txtseatsavail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 210, 30));

        date1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        date1.setText("Seats Available");
        jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 425, -1, -1));

        date2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        date2.setText("Ticket Prize");
        jPanel1.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 486, -1, -1));
        jPanel1.add(txtprize, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 482, 207, 31));

        ok.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel1.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 531, -1, -1));

        exit.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 531, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\java programs\\Project Reqirements\\Images\\Edited files\\edited-600-580.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbusActionPerformed

    private void txttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimeActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        
    }//GEN-LAST:event_exitActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
String bus=txtbus.getSelectedItem().toString();
String location=txtlocation.getSelectedItem().toString();
String time=txttime.getText();
String ac=txtac.getSelectedItem().toString();
SimpleDateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
String date=dateformat.format(txtdate.getDate());
int Seaava=Integer.parseInt(txtseatsavail.getText());
int Ticketpri=Integer.parseInt(txtprize.getText());
int seatno=0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/bus_ticket_booking","root","");
            Statement st=con.createStatement();
           
            
            for(int i=1;i<=Seaava;i++)
            {
                String seats="UnBooked";
                seatno=seatno+1;
                
            PreparedStatement pst=con.prepareStatement("insert into account_control values(?,?,?,?,?,?,?,?)");
            pst.setString(1, bus);
            pst.setString(2, location);
            pst.setString(3, time);
            pst.setString(4, ac);
            pst.setString(5, date);
            pst.setInt(6, seatno);
            pst.setString(7, seats);
            pst.setInt(8, Ticketpri);
            pst.executeUpdate();
            }
            JOptionPane.showMessageDialog(this,"Tickets Updated");
            con.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Admin_Control.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Control.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
    }//GEN-LAST:event_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Control().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminControl;
    private javax.swing.JLabel Travelsname;
    private javax.swing.JLabel ac;
    private javax.swing.JLabel date;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel location;
    private javax.swing.JButton ok;
    private javax.swing.JLabel time;
    private javax.swing.JComboBox<String> txtac;
    private javax.swing.JComboBox<String> txtbus;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JComboBox<String> txtlocation;
    private javax.swing.JTextField txtprize;
    private javax.swing.JTextField txtseatsavail;
    private javax.swing.JTextField txttime;
    // End of variables declaration//GEN-END:variables
}
