/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus_ticket_booking;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harid
 */
public class Busses_Available extends javax.swing.JFrame {

    /**
     * Creates new form User_Details
     */
    public Busses_Available() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtdate = new com.toedter.calendar.JDateChooser();
        txtloca = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        check = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bustable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txttprize = new javax.swing.JTextField();
        txtphnno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        booktickets = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txttname = new javax.swing.JTextField();
        txttime = new javax.swing.JTextField();
        txttdate = new javax.swing.JTextField();
        txttloca = new javax.swing.JTextField();
        txtac = new javax.swing.JTextField();
        txtseatno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtdate.setDateFormatString("yyyy-MM-dd");
        txtdate.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jPanel1.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 85, 126, 32));

        txtloca.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txtloca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pollachi-Chennai", "Coimbatore-Chennai", "Coimbatore-Madurai", "Madurai-Coimbatore" }));
        jPanel1.add(txtloca, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 84, 180, 33));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setText("Choose Date");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 85, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Busses Available");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setText("Starting  & Droping Point");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 90, -1, -1));

        check.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        check.setText("Check Busses");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        jPanel1.add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 128, -1, 38));

        bustable.setBackground(new java.awt.Color(204, 204, 255));
        bustable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Travels Name", "Location", "Time", "Ac", "Date", "Seat NO", "Seats Available", "Ticket Prize"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bustable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bustableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bustable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 184, 780, 120));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel4.setText("Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel5.setText("Phone No");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        txttprize.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txttprize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttprizeActionPerformed(evt);
            }
        });
        jPanel1.add(txttprize, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 220, -1));

        txtphnno.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txtphnno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphnnoActionPerformed(evt);
            }
        });
        jPanel1.add(txtphnno, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 189, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel6.setText("Seat No");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel8.setText("Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 70, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel9.setText("Travels Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 160, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel10.setText("Location");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 100, -1));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel11.setText("AC");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 50, -1));

        booktickets.setBackground(new java.awt.Color(255, 153, 204));
        booktickets.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        booktickets.setText("OK");
        booktickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookticketsActionPerformed(evt);
            }
        });
        jPanel1.add(booktickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, 70, 31));

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, -1, 30));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel12.setText("Time");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 60, -1));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel13.setText("Ticket prize");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 150, -1));

        txtname.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 220, -1));

        txttname.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jPanel1.add(txttname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 220, -1));

        txttime.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jPanel1.add(txttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 220, -1));

        txttdate.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jPanel1.add(txttdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 220, -1));

        txttloca.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txttloca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttlocaActionPerformed(evt);
            }
        });
        jPanel1.add(txttloca, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 189, -1));

        txtac.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txtac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtacActionPerformed(evt);
            }
        });
        jPanel1.add(txtac, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 189, -1));

        txtseatno.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        txtseatno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtseatnoActionPerformed(evt);
            }
        });
        jPanel1.add(txtseatno, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 189, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\java programs\\Project Reqirements\\Images\\Edited files\\804-683.jpg")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
SimpleDateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
String date=dateformat.format(txtdate.getDate());
String location=txtloca.getSelectedItem().toString();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/bus_ticket_booking","root","");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("Select * from account_control");
            while(rs.next())
                    {
              if(date.equals(rs.getString(5))&&location.equals(rs.getString(2)))
              {
             String tname=rs.getString("Travelsname");
             String loca=rs.getString("Location");
             String time=rs.getString("Time");
             String ac=rs.getString("Ac");
             String dat=rs.getString("Date");
             String seatno=String.valueOf(rs.getInt("SeatNo"));
             String seatsava=rs.getString("SeatsAvailable");
             String ticketpri=String.valueOf(rs.getInt("TicketPrize"));
             String table[]={tname,loca,time,ac,dat,seatno,seatsava,ticketpri};
             DefaultTableModel model=(DefaultTableModel)bustable.getModel();
             model.addRow(table);
              }
                    }
            con.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Busses_Available.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Busses_Available.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_checkActionPerformed

    private void txtphnnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphnnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphnnoActionPerformed

    private void bookticketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookticketsActionPerformed
       String seatavailable="Booked";
       
        try {
            // TODO add your handling code here:
          
            int seatno=Integer.parseInt(txtseatno.getText());
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/bus_ticket_booking","root","");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from account_control");
            while(rs.next())
            {
                if(seatno==rs.getInt(6))
                {
                    PreparedStatement pst=con.prepareStatement("update account_control set SeatsAvailable=? where SeatNo=?");
                    pst.setString(1, seatavailable);
                    pst.setInt(2, seatno);
                    pst.executeUpdate();
                }
            }
    String name=txtname.getText();
    String phnno=txtphnno.getText();
    int seat=Integer.parseInt(txtseatno.getText());
    String travelsname=txttname.getText();
    String loca=txttloca.getText();
    String time=txttime.getText();
    String ac=txtac.getText();
    String date=txttdate.getText();
    String prize=txttprize.getText();
    PreparedStatement pst=con.prepareStatement("insert into User_Details values(?,?,?,?,?,?,?,?,?)");
    pst.setString(1, name);
    pst.setString(2, phnno);
    pst.setInt(3, seat);
    pst.setString(4, travelsname);
    pst.setString(5,loca);
    pst.setString(6,time);
    pst.setString(7,ac);
    pst.setString(8,date);
    pst.setString(9,prize);
    pst.executeUpdate();
    con.close();
    JOptionPane.showMessageDialog(this,"Make Payment");
    Price_details pd=new Price_details();
    pd.setVisible(true);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Busses_Available.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Busses_Available.class.getName()).log(Level.SEVERE, null, ex);
        }
   
        
        
    }//GEN-LAST:event_bookticketsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txttprizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttprizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttprizeActionPerformed

    private void txttlocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttlocaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttlocaActionPerformed

    private void txtacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtacActionPerformed

    private void txtseatnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtseatnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtseatnoActionPerformed

    private void bustableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bustableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)bustable.getModel();
        int index=bustable.getSelectedRow();
        txttname.setText(model.getValueAt(index, 0).toString());
        txttloca.setText(model.getValueAt(index, 1).toString());
        txttime.setText(model.getValueAt(index, 2).toString());
        txtac.setText(model.getValueAt(index, 3).toString());
        txttdate.setText(model.getValueAt(index, 4).toString());
        txtseatno.setText(model.getValueAt(index, 5).toString());
        txttprize.setText(model.getValueAt(index, 7).toString());
    }//GEN-LAST:event_bustableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busses_Available.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busses_Available.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busses_Available.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busses_Available.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busses_Available().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton booktickets;
    private javax.swing.JTable bustable;
    private javax.swing.JButton check;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtac;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JComboBox<String> txtloca;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphnno;
    private javax.swing.JTextField txtseatno;
    private javax.swing.JTextField txttdate;
    private javax.swing.JTextField txttime;
    private javax.swing.JTextField txttloca;
    private javax.swing.JTextField txttname;
    private javax.swing.JTextField txttprize;
    // End of variables declaration//GEN-END:variables
}
