/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus_ticket_booking;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author harid
 */
public class User_Changepass extends javax.swing.JFrame {

    /**
     * Creates new form User_Changepass
     */
    public User_Changepass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        changepass = new javax.swing.JLabel();
        newpass = new javax.swing.JLabel();
        newpass1 = new javax.swing.JLabel();
        txtnewpass = new javax.swing.JPasswordField();
        txtnewcpass = new javax.swing.JPasswordField();
        ok = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        phn = new javax.swing.JLabel();
        txtphn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        changepass.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        changepass.setText("Change Password");
        jPanel1.add(changepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        newpass.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        newpass.setText("New Password");
        jPanel1.add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        newpass1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        newpass1.setText("Confirm Password");
        jPanel1.add(newpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        txtnewpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnewpassActionPerformed(evt);
            }
        });
        jPanel1.add(txtnewpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 170, 30));

        txtnewcpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnewcpassActionPerformed(evt);
            }
        });
        jPanel1.add(txtnewcpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 170, 30));

        ok.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel1.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        exit.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        phn.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        phn.setText("Phone No");
        jPanel1.add(phn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));
        jPanel1.add(txtphn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 170, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\java programs\\Project Reqirements\\Images\\Edited files\\4d845686128681.5d909dad4ddd3.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 510, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnewpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnewpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnewpassActionPerformed

    private void txtnewcpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnewcpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnewcpassActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        String pass= txtnewpass.getText();
        String cpass=txtnewcpass.getText();
        int phn=Integer.parseInt(txtphn.getText());
        if(pass.equals(cpass))
        {

            try {
                
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost/bus_ticket_booking","root","");
                PreparedStatement pst=con.prepareStatement("Update user_accountcreatiom set Password=?,ConfirmPassword=? where MobileNo=?");
                pst.setString(1, pass);
                pst.setString(2, cpass);
                pst.setInt(3, phn);
                pst.executeUpdate();
                con.close();
                JOptionPane.showMessageDialog(exit,"PasswordUpdated");

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Admin_Changepass.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Admin_Changepass.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }

        else
        {
            JOptionPane.showMessageDialog(this,"Fields Not Matched");
        }

    }//GEN-LAST:event_okActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Changepass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel changepass;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel newpass;
    private javax.swing.JLabel newpass1;
    private javax.swing.JButton ok;
    private javax.swing.JLabel phn;
    private javax.swing.JPasswordField txtnewcpass;
    private javax.swing.JPasswordField txtnewpass;
    private javax.swing.JTextField txtphn;
    // End of variables declaration//GEN-END:variables
}
